### PR TITLE
Solved issue #130 and #131

### PR DESCRIPTION
**Pull request by SattyamSamania**
## Issue Number:
- Here goes the issue number with a #130 and #131
-----------------------------------------------------------
## Issue Description:
- Describe the issue fixed here
-----------------------------------------------------------
## Additional Information (Optional):
- Type the additional information here
- Hey @shelcia I have added two issues just check what should be the proper sidebar position.
-----------------------------------------------------------
## Checklist:
- [x] Testing
- [x] No conflicts with the main branch
- [x] Documentation
-----------------------------------------------------------
## Screenshot of the changes:
Earlier | Current
--------|----------

### CODE REVIEW

**Review by shelcia — APPROVED** [review]

**Comment by shelcia** [comment]
resolve conflicts

**Comment by SattyamSamania** [comment]
> resolve conflicts

@shelcia What other changes should I have to do now?

**Comment by shelcia** [comment]
resolve conflicts

**Comment by SattyamSamania** [comment]
> 
> resolve conflicts
> 
> 

@shelcia The option is of Resolve Conflicts is hidden.

**Comment by shelcia** [comment]
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b SattyamSamania-feature master
git pull https://github.com/SattyamSamania/noobcodes-docs.git feature
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff SattyamSamania-feature
git push origin master

**Comment by SattyamSamania** [comment]
@shelcia Does it create a problem if I push the master branch?

**Comment by shelcia** [comment]
> @shelcia Does it create a problem if I push the master branch?

you cannot push it to master directly you will have to create PR

**Comment by SattyamSamania** [comment]
@shelcia I have done the steps  mentioned by you.

**Comment by shelcia** [comment]
the conflicts aren't resolved

**Pull request closed without merging**
